CREATE DATABASE QUANLYRAPPHIM
GO
USE QUANLYRAPPHIM
GO
DROP DATABASE QUANLYRAPPHIM
GO
CREATE TABLE NHANVIEN
(
	Id NVARCHAR(10) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
	Pass NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	Sdt INT NOT NULL,
	NgaySinh DATE NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Vitri NVARCHAR(50) NOT NULL,
	Luong INT NOT NULL
)
CREATE TABLE KHACHHANG
(
	Id NVARCHAR(10) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
	Pass NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	Sdt INT NOT NULL,
	NgaySinh DATE NOT NULL,
	Email NVARCHAR(100) NOT NULL
)
CREATE TABLE PHIM
(
	Id NVARCHAR(10) PRIMARY KEY,
	Ten NVARCHAR(100) NOT NULL,
	HinhAnh NVARCHAR(100) NOT NULL,
	NgayKhoiChieu DATE NOT NULL,
	ThoiLuong NVARCHAR(50) NOT NULL,
	Rated FLOAT NOT NULL,
	TheLoai NVARCHAR(100) NOT NULL,
	NgonNgu NVARCHAR(100) NOT NULL,
	DienVien NVARCHAR(100) NOT NULL,
	DaoDien NVARCHAR(100) NOT NULL
)
CREATE TABLE PHONG
(
	Id NVARCHAR(10) PRIMARY KEY,
	TenPhong NVARCHAR(50) NOT NULL,
	SucChua INT NOT NULL,
	DienTich NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(100) NOT NULL
)
CREATE TABLE GHE
(
	Id NVARCHAR(10) PRIMARY KEY,
	TenGhe NVARCHAR(100) NOT NULL,
	Hang NVARCHAR(100) NOT NULL,
	IdPhong NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHONG(Id)
)
CREATE TABLE LICHCHIEU
(
	Id NVARCHAR(10) PRIMARY KEY,
	MoTa NVARCHAR(100) NOT NULL,
	IdPhim NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHIM(Id),
	IdPhong NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHONG(Id)
)
CREATE TABLE VE
(
	Id NVARCHAR(10) PRIMARY KEY,
	GiaTien MONEY NOT NULL,
	MaQR NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(100) NOT NULL,
	IdGhe NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES GHE(Id),
	IdLichChieu NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LICHCHIEU(Id)	
)
CREATE TABLE HOADON
(
	Id NVARCHAR(10) PRIMARY KEY,
	NgayGioThanhToan DATE NOT NULL,
	TongTien MONEY NOT NULL,
	IdNhanVien NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(Id),
	IdVe NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES VE(Id),
	IdKhachHang NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES KHACHHANG(Id),
)